version: 2
builds:
- id: jumpie-linux-amd64
  binary: jumpie
  builder: prebuilt
  goos:
  - linux
  goarch:
  - amd64
  prebuilt:
    path: dist/jumpie-linux-amd64/jumpie
- id: jumpie-darwin-amd64
  binary: jumpie
  builder: prebuilt
  goos:
  - darwin
  goarch:
  - amd64
  prebuilt:
    path: dist/jumpie-darwin-amd64/jumpie
- id: jumpie-darwin-arm64
  binary: jumpie
  builder: prebuilt
  goos:
  - darwin
  goarch:
  - arm64
  prebuilt:
    path: dist/jumpie-darwin-arm64/jumpie
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: tituscarl
    name: jumpie
brews:
- repository:
    owner: tituscarl
    name: homebrew-tap
  name: jumpie
  homepage: "https://github.com/tituscarl/jumpie"
  description: "A fun terminal-based jumping game inspired by the Chrome dinosaur game"
  directory: Formula
  install: |
    bin.install "jumpie"
  test: |
    assert_match "jumpie", shell_output("#{bin}/jumpie --version", 0)